apiVersion: v1
kind: Service
metadata:
  name: {{include "easy-tunnel-lb.fullname" .}}
  labels:
    {{- include "easy-tunnel-lb.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{.Values.config.healthCheckPort}}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "easy-tunnel-lb.selectorLabels" . | nindent 4}}
