name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Charts
        run: |
          mkdir .cr-release-packages
          helm package charts/* --destination .cr-release-packages

      - name: Create gh-pages branch if not exists
        run: |
          if ! git rev-parse --verify gh-pages >/dev/null 2>&1; then
            git checkout --orphan gh-pages
            git rm -rf .
            git commit --allow-empty -m "Create gh-pages branch"
            git push origin gh-pages
          fi

      - name: Generate Helm Repository
        run: |
          git checkout gh-pages
          cp .cr-release-packages/* .
          helm repo index . --url https://quinnovator.github.io/easy-tunnel-lb
          git add .
          git commit -m "Update Helm repository" || echo "No changes to commit"
          git push origin gh-pages

      - name: Switch back to main
        run: |
          git checkout main 