name: Build, Test, and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/quinnovator/easy-tunnel-lb:alpha
            ghcr.io/quinnovator/easy-tunnel-lb:${{ github.sha }}

      - name: Build Release Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o easy-tunnel-lb-linux-amd64 ./cmd
          GOOS=darwin GOARCH=amd64 go build -o easy-tunnel-lb-darwin-amd64 ./cmd
          GOOS=darwin GOARCH=arm64 go build -o easy-tunnel-lb-darwin-arm64 ./cmd

      - name: Generate Release Tag
        id: tag
        run: |
          echo "tag_name=v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          files: |
            easy-tunnel-lb-linux-amd64
            easy-tunnel-lb-darwin-amd64
            easy-tunnel-lb-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true
