name: Build, Test, and Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Build Release Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o easy-tunnel-lb-linux-amd64 ./cmd/easy-tunnel-lb
          GOOS=darwin GOARCH=amd64 go build -o easy-tunnel-lb-darwin-amd64 ./cmd/easy-tunnel-lb
          GOOS=darwin GOARCH=arm64 go build -o easy-tunnel-lb-darwin-arm64 ./cmd/easy-tunnel-lb

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            easy-tunnel-lb-linux-amd64
            easy-tunnel-lb-darwin-amd64
            easy-tunnel-lb-darwin-arm64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
